[WIP][T6811]bad_connector_woocommerce:Export Stock update BAD-SIP.
BizzAppDev-Systems/connector-woocommerce pull request #51
Opened 2023-10-20 10:00 UTC by bizzappdevteam

2023-10-25 05:04 UTC, bizzappdev requested changes

2023-10-25 05:04 UTC, bizzappdev commented on bad_connector_woocommerce/models/product/common.py
> +def chunks(items, length):
move this to utils

2023-10-25 05:04 UTC, bizzappdev commented on bad_connector_woocommerce/models/product/common.py
> +    RECOMPUTE_QTY_STEP = 1000  # products at a time
make it configurable from backend

2023-10-25 05:04 UTC, bizzappdev commented on bad_connector_woocommerce/models/product/common.py
> +        """Import Product Attribute Value"""
proper doc string

2023-10-25 05:04 UTC, bizzappdev commented on bad_connector_woocommerce/models/product/common.py
> +        return True
```suggestion
        backends = defaultdict(self.env['woo.product.product'])
        for woo_product in self:
            backends[woo_product.backend_id] |= woo_product
        for backend, woo_products in backends.items():
            self._recompute_woo_qty_backend(backend, woo_products)
        return True
```

2023-10-25 05:04 UTC, bizzappdev commented on bad_connector_woocommerce/models/product/common.py
> +                if new_qty != product["woo_product_qty"]:
use if not continue

2023-10-25 05:04 UTC, bizzappdev commented on bad_connector_woocommerce/models/product/importer.py
> +    def run(self, binding, fields):
have the exact signature from the exporter

2023-10-25 05:04 UTC, bizzappdev commented on bad_connector_woocommerce/models/woo_backend/common.py
> +            ("type", "!=", "service"),
better to add stock and IMO it is not type by detailed type

2023-10-25 05:04 UTC, bizzappdev commented on bad_connector_woocommerce/models/product/importer.py
> +        return {"stock_management": record.get("manage_stock")}
if manage stock is true then also set proper product type

2023-10-25 10:06 UTC, bizzappdev requested changes

2023-10-25 10:06 UTC, bizzappdev commented on bad_connector_woocommerce/models/product/common.py
> +        else:
remove this condition and have it from warehouse always

2023-10-25 10:06 UTC, bizzappdev commented on bad_connector_woocommerce/models/product/common.py
> +        self_with_location = self.with_context(location=location.id)
sudo

2023-10-25 10:06 UTC, bizzappdev commented on bad_connector_woocommerce/models/product/common.py
> +            for product in records.read(fields=product_fields):
use browse instead

2023-10-25 11:01 UTC, bizzappdev requested changes

2023-10-25 11:01 UTC, bizzappdev commented on bad_connector_woocommerce/models/product/common.py
> +                self.browse(product["id"]).woo_product_qty = new_qty
```suggestion
                product.woo_product_qty = new_qty
```

2023-10-30 11:35 UTC, bizzappdev commented on bad_connector_woocommerce/migrations/16.0.3.0.1/post-migration.py
> +def migrate(cr, version):
no need for migration script make field required only from view

2023-11-27 10:12 UTC, bizzappdevteam commented
This PR is merged in #52.

2023-11-27 10:12 UTC, closed without merging