[WIP][T6815]bad_connector_woocommerce: Auto Sale Order confirmation BAD-SIP
BizzAppDev-Systems/connector-woocommerce pull request #55
Opened 2023-10-26 08:16 UTC by bizzappdevteam

2023-10-27 05:32 UTC, bizzappdev requested changes

2023-10-27 05:32 UTC, bizzappdev commented on bad_connector_woocommerce/models/sale_order/importer.py
> +        )
either have one method for payment mode and process id or have common method for searching

2023-11-01 15:30 UTC, bizzappdev commented on bad_connector_woocommerce/models/woo_backend/common.py
> +        return [("category_id", "=", category_id.id)]
move all default functions before defining the fields

2023-11-27 11:06 UTC, bizzappdevteam commented
This PR is merged in #58.

2023-11-27 11:06 UTC, closed without merging